kubernetes:
  children:
    master:
      hosts:
        k8s-1:
          ansible_host: 192.168.0.22
        k8s-2:
          ansible_host: 192.168.0.23
        k8s-3:
          ansible_host: 192.168.0.24
    worker:
      hosts:
        k8s-0:
          ansible_host: 192.168.0.21
