# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: monica-secrets
    namespace: home
stringData:
    APP_KEY: ENC[AES256_GCM,data:AxwMaJ1ApUYpGS7Aq5GQl70mxuayuqxRxDpl8zClENT1hKk9pDWOEQ==,iv:L4KDS1rQswh0SypHIyfgpqQvyCniaeesXX+XpE3f5Iw=,tag:dESlIfTyi/vARJa39Hqq9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-30T21:08:26Z"
    mac: ENC[AES256_GCM,data:fhdhSN9C+TSI9P7ADjWsNVPXq2eFtuXfEV3xmJ3iIPO1d8VkVk8A6YRdRneSeVuD4dROx4vudd4bNvHWGOy3oK1GM7yTEYz2WhPm+t28XADwZFGDSUbwwPeA71tChNtqw/GE6C4ovPgn6UGC/bxTEBu8xKHxIdBtzAbv2xOunXM=,iv:rWBUpEceIYm8D1YfZmlGIFPz69s5MpiaaV+cuQBkhek=,tag:is7BQ/ofAqQmEoOPL2lHAA==,type:str]
    pgp:
        - created_at: "2021-11-30T21:08:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxaBx94v0M+OARAAopWZOUItVH0liYXAVpQS0LgaCjphdrVKrlziXEE6pWFA
            9Ph/BoslXaqYn/vvVT20JHcpYWKCFPw+RhVhjCHwbIgfyhGVBcfnPYPl0GmDSmI4
            fboPfvxdfrPbgO1tty2tAsNIB142p2zJaMavYwRYi6y/H+ZeqE61LHUjemHZdxzz
            7LOxwALqJMqsLaalUI7elaH/ffVlIT+kLrYBk0lkFUMYw6IOWIe9FxE2Uiwck627
            Wwi7dYg7KksB/2ZB7V02CnqhnBCrjm/byXH4R7IJeOXP68Mortiv8w+o3kFZoOZ5
            9NCN4NYgXRAcC3ZE/IaLb9YJDgLbmsRz05pajZsYNqeV7WpBIo7zwCEj5hYjt4pP
            8o/TZkQ7w81QuavDSJAK3BWUtEeB/qwTSjTL1LpJ+Sr46Y/NM3AOdEPEHbfcZsSs
            +2znm6t7v55dmw9jlQJC6Vvh1WOzDtb6VQet9UqEIqXd+5U8igqjg8T6xrlFLlni
            XqQvDDY9t0ZT75v6qHxRNc2/uqvCSRF5jLCeeI7kOvhrWVmMPgqtWrBDXzhzeFY2
            wuxSE4Tk69DWGFQ+T+mZ4S356EssRg+V9W97pxEnn2gB56PT7FzBWiTeVs7iO7/N
            wu6jEx5u64HhztYqIQWMRcXdGchTOmROzC9jWnh2dJINe4N/86J+nmU8GLB4V0DU
            aAEJAhCg9P2x1Akyf38KqnBHiDjsBtY0DbOxaivUwObo7l5e9Z06534tyYHThAA+
            TweNh3EMTD68R32nLm21Shnj8a/5+KckIQaQa4WYkBcKjmvqFIORusOP5SxnGXMc
            x9m3nVTtXPUO
            =8Nml
            -----END PGP MESSAGE-----
          fp: 0F778AB50C03EB5A23877A080943CC1360A9D7F0
        - created_at: "2021-11-30T21:08:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5xaOfZxjCipARAAr/ARKz06SSjbFs3AovxISFiUK0lJp0wMaizkFG/4IaOV
            DUyZX2HLgH86ihpBar4X4klCTQA1kbkNfB3XEoZx6MLh2to7eZPRJd788SdypmnJ
            Luhz+fVxJEvcnebl0iI+wdQ9UfO16ukapIeN9enU7/aEyWtaUudowB+xPP8yg9eB
            h+3mIonVWBSL2Z27hnLzJ3QVWkmdVBwJ2gJYWG+aEdA9voaAJhney4TB63irua4h
            FhVFBO9piowlsePFl18Ef6ADmllSr+fy2J2fipYVVf2x9zaMz/sjxhpXwCY1FTPF
            VeHQDtvo9p/d2uZLh0kzE6mOq9teNEs3ROIXNvCqltM/ZNXzrTlWmamZ8EUyfm3M
            pqeLYVzimqirDNSL65tQG1gyUqW+naVs4gg01dbs7czPTkX0EhrMXHIYFoP5732E
            vkycAxQ4wVyDt9tyibLOAazsgW+gBvzAkwrfPig7nREebZQ7ahkwqybwHICtcpdu
            TCQLhNXG1oeagE0A+UWvChNzrwzdcEqZ+uIPVhjdhbPYqm6wGHYzDgYjJ8W3SivJ
            tnKvyprWt4LNBdk7w9548+INZtSYgT7O6dv5IPVVXulDWH9TnVU+ps2UwT7dkQJa
            DFbH3AlPj0/VS3z1vtvjU1N2P5l/+BVLOS7v4w3bmStGKNfseBqVnC2MvAxnLmbU
            aAEJAhBoXvbYnxR7eyXOc78aD4b7WMMOTpPajimqDLRJ/xXryfIwRPHBpxsOZvwK
            zDZUjZ76BZZydNipSOUJM8wFgeaVRWnKuVcUIVugAWZE/FxGJ8hVYloYo4wdckCi
            v4h/nshKykOq
            =c07V
            -----END PGP MESSAGE-----
          fp: 6EC154334B8BA3FFD4E62F305112A42499373600
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
