kind: Secret
ansible_user: ENC[AES256_GCM,data:G2LW,iv:lrzMXCuN5qsldNqWlGZ8B9eLykD6sIbtRZ3MHkR/+ic=,tag:Tzx+BKo1jmhc6mCVd9UvLQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:d7CYWp7XZepX,iv:4UOKDWa2BqDLThVD5YDy//dboNyi72henOybkEsx2jA=,tag:u+FmuAVK4mGHQuSKiZZpNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-28T16:42:23Z"
    mac: ENC[AES256_GCM,data:uTWKX+Qp2jHhls0S9KD+cGeDp6cNrmjnxS8erFeMXiz1eWYZ+i0SPVN4byqg040IupSD+1t9ul+s2qpUdQ7XgXiKeyod24UeuxbxDqgcp8T50p5ZrSbtanOWDrVVEtTMi/Sm4HbSgt+LqrPgMyX3uXihSOHiFkjhfxSgFqaMUsQ=,iv:EqZNhnUWQspiEYygBVQmNvbXAZAtL9ve00ICUfxakkg=,tag:gY70a7n95utU7WM73cDK9Q==,type:str]
    pgp:
        - created_at: "2021-10-28T16:42:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5xaOfZxjCipAQ//ZOtqJwpGEDllvrxK2jbVJlXq8Vy1roV1RHR2vhd3AUAR
            MI+MGoeCAT/Fl9WjgEkhYbv+WYTkR9njYrzHtDHDfvh4zLW0Gi0dA+30HnJ260c8
            eFZm0PlD448hEyz9L4rRMslv+jAx9kKhrxQundlshI65KIgwnvC3SLpjgozg/o+s
            +a4+QfOJWnKYJcsYjfq5WNzJNC3tkpViF9lEuk8JNQw6JKmxpbwr8tYOiN/bK9+k
            sajfFYYD/t+72LHoJdP/EzUUCr9LtdmtKlj99J+/iv5xdt0zyRK6yH3LTb/Kdw0x
            AUeHifXhpyKiHFMRguXY6mBQkhCnymgO3POlUjbDBiVE8OlrgH+NjenFabqzAJ+f
            5RVtfhdkLHZVu3rE4byZR66hmHe7NvvRfUqCRS3lcxfApxXzVDUd1IVg9gtXjqKa
            SjpRzLlzyEhtEPs/ekHHp0xC6HpsmPwNfphM9LBZ1tPHGuXF+p0HK9u+2LDBuzBN
            K02atJITnJTZrSGZYSHHg7R1y9/3UKEeAcCTP5qG0NuhVjz2cNAmTaJ2z7eI4PA9
            V1aDU+JFx8asZSbSM9NtJ+iQaiI9ffQ7c4Dl73h/22EdJAWNPGGNltWBzPpQNO6O
            2gJ/mSaokQmHfdlqrN9McuoOsGQYwxHIDEkdUg6Vg3k3gOhgBV/0oJEAP9INVuXU
            aAEJAhXx2PvL+koM+DPM4ZugjvSTupQvJYCr45mVxStw3hyFuPrXNiMGoKoHvyGv
            nPCtPa1pMQNzuaEcVnlYr40/KJPcf8ikFbh/SXwhzLNxs7fKPItfqP4sxNmztnFJ
            a/dPoH0p9P21
            =DJnE
            -----END PGP MESSAGE-----
          fp: 6EC154334B8BA3FFD4E62F305112A42499373600
    unencrypted_regex: ^(kind)$
    version: 3.7.1
