# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cvault-secrets
    namespace: home
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:TRV2oxTCmX5+Z5SsOU+9d5qKLo8+57yQ9Na4RavGlVq2jn53Ppssaw==,iv:mWAIwjMKO3jT9XFIgLQlM0mfQAap1Yw1sT3ST1caEKI=,tag:SD6PUTjU8kzkWnDB9zIQrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-30T12:24:49Z"
    mac: ENC[AES256_GCM,data:pNmbrOKMOAx75BcR1V6pAZUeS55CcSk/9DuGmLK9gky42OuqFBSytJyuVjSpSvpS3plZu1T6hYEG7TkdAAqaiRPsbXQd+IYoXSKSn5iUG9ubmXX1kPu5PauvdZspGfUKTsGSsqZxZyfy+ec7tSuu8CAjUgs5BBDPTy9QuMYQo5E=,iv:Da3zT+gUxGjhRs6DNYQoUGPSsVV2Q6HODTyiD79SRE4=,tag:KtLZKWkmbfER3UHmPyxBRw==,type:str]
    pgp:
        - created_at: "2021-11-30T12:24:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxaBx94v0M+OARAAgNJQy5cOpx8pC67NDdcAyksCSTIC7dEzT0CPWTvmtQHQ
            7+q516ttoSzUy+AtC7/GbKgLIYMPZ+56ihmDKHctClMBLoVmu+Yj3AKI8xkXmFOG
            iKH1nlCWy42JXG4kRb3qB3qdczQE2StdtF1mDKzm/4GXbs351HteRtFVYBY3dwd2
            yH8O4xduOm6UOTWF/LZwhy0kLu5bEoJLD3H5Ej5pXw0M4JT/XcZ1E2O+HObgz3VO
            MXsarjLh0xhCu9Zb6bbNRH77/pOwdmdWIP3emD3UOeI11NtzQ/W7hBCxK6aXIuLu
            KFUfaXkYl5eZ3UPqguJzUqFYSGX0VwYpfwkQ621qSPvKHqTNCqaNGfggs0mqq4vP
            g9XS2yc1kkS/WqSeUbBFa6OeVddXBTenR+od67ygagfperfpgRT0HmNsl6UP+k/o
            1SlrtDGA7mLG18utxoQv9I3tm6qEFgwSKdPt1jg2pg6eMeUZezV+EvJa2ysUVHtd
            gyhpqzH8vlQVhOgVNM5g0LITpknCUStkcQurRpr5uQFzU4gwSiAbstFqnL+OVENa
            BdezCMN4smw5x8ifP4p1T7QrVrWZEpNztIIz9MQ3SJnzHQ4aNXefh9XUZf2LYYVu
            S3mTGj1iy65u2BjYPWFNU046/vzDEMWLbT8GNv66OqjZ5l6zCMO2h3jjmgMmwkbU
            aAEJAhDGjoJ2cfHaQROvW33TXUAvgO3acJQjpaeoub7IlHJIZt8BHMZwwSmxv1ly
            /2TFGVcciET0Dzbv0NhJ9Vyh+106LV/JjQ067agMNjFDi3JdLTHqDjmR2dIXxNeF
            7nHDykb6CB+p
            =KD/y
            -----END PGP MESSAGE-----
          fp: 0F778AB50C03EB5A23877A080943CC1360A9D7F0
        - created_at: "2021-11-30T12:24:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5xaOfZxjCipARAApZIiGmoY5IP8LOz7UYg6GhJEEj4Y6rjF5y8GpDCuVl/p
            F2Et2zIYdPBA2FnKR1AtDOf+NYRP0ZRuAvpBSaCtfv9AwWiU6WfeWCZ3XBfOwilC
            cBJL/goQWvPeao4HNzHs2OOB34ppOc0/aT28YVuC6Jxbp4cjouRmOxUcw3gY97Gd
            IpYg39sabYQwY2Z8l2NiCbEQ6tnHo/Z1bvm+LFGObONzQHWMb9avQOoFBzC6gA5d
            pRuD6eg8NSGn0lEN9qMsStjdmZgcfHZZvZthA6nB6UGFaIWTZTGVXKi+qte2+FNO
            JCzVB1FRC0iLbJc8lcIEou97Y1knViBwA6tFqDysw37Qyz3019gERQTiwrJ0hAWm
            wbFqFhn1pf89Du9zxrv7NmgODHWm0KKQhw1KWK8lgZ3n1RYvBguJmsNlR4PRwOSV
            AtN1RnWZAsiTQiBQ6fproHfCEYSQCIYfXBd+Dq73tR1XmapjqNqMIlzkEZCKwFwn
            D/esonORZR2M6jqUDcJEHogdPC0WCVv6tuO99OK4OX9R6znjat0HF5LvnO3HBoun
            9z3kpHMbA41Gtm6c1TzhbwocYekjl6cFq4OUi865ePQaUwpjBXV9wIkmcS+WnYGd
            kHXRPEcuOeK0ttf/w0QdLZdaERStwXVuiIDtqzfRWfSNyEhjOjbiKqFSfesE/EXU
            aAEJAhAg0gcowp69+WNGJkoWVkX4bvlxa/zHPCHdWG2z/RGCoCh4xHUjW4+mYHwN
            42aEKsdV1TlTXIOyqOhr9KNHr4XK8gD7e1aMGFj24ILr0a03CoC2Il3iSCLohY8z
            RAJ4Jtc2uYi4
            =S5qh
            -----END PGP MESSAGE-----
          fp: 6EC154334B8BA3FFD4E62F305112A42499373600
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
