# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:O6+GNxN+DFI5Sn3ovseH25oxgefgk66qOIqY3uJl9EAbd1872A==,iv:uQAFDFFPFOUp40gSB92AUqKFDbEVNg35xsRDsbz2lCA=,tag:3uzSFnhj+bEFGkRyerOxHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-28T16:42:20Z"
    mac: ENC[AES256_GCM,data:A+R2/1LgCygNnYLt60h2VLXA4B8FWb/1L2biTFOL+c+titmLMu+9ewBFF4XaIYiwKEn6xTaEwoAW7u3OW3Dnw8N/A7He2Zn6cOGUAD7BLt578F5ftjYCga0drDEDRI35enF8bwOHYfgoYRT4oj1syRC5vbp8lHFWcr6jL4Ssb/E=,iv:barJJHZ9OCdMG1695oo+vwxMKkcd56kiQOzZkuzLKzQ=,tag:BZBZawhO6ZLRHpDNpHrybw==,type:str]
    pgp:
        - created_at: "2021-10-28T16:42:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxaBx94v0M+OAQ//VmdtgOAKCgLnezLQ3dseEsu727skh1rIOuadJp+4a1yZ
            Ovc0nEcpwkR0HxaK9QB4fHnoQFAP4/LVs4l3hIGOZC3NyHhaQhqjpPrDWhRcs+od
            zpexbNZNGeSIBSUe/JBVjHnrnwhAqWVzQ4fO4OI9LpfBDDz5qnXBVGfsH/zWPmST
            q/ozLz26HKJ7HPzarCu+gOOug0bM1q6VN0wfLe0QUTyUgJqovcaUhSlUkTs8Gxdl
            hehlxsDiQaWg5T5IP2sgrMZpK4uzCHaxgMOnsSCeBIhh2cU4LE8IutaYQsAaJ1yd
            N84Cld05giY02ab8saMoPHhuJ3WH/BWLjDWv/CUv+F9Mk5OoUj5yFVy18ztyDNkG
            dsS3ccwi1U4g+NUsS1daoND63Yo/PA6V4f3oz+/7imsB7La1SLors4gz2p6vsbia
            8omT7zFRUU7aCb8m3/96JCmOokEt7z1eydkUhX2S6NACa9L5IkYZDUsyyC8hXoZG
            Gvxpfj55VqYF6rSz/DXq+zegrdRz3h89AXuXkCmhVIrcLyx69/YyVYmQUuB4bMNS
            8SMp3iU2FiSD1jazPtz49ulm75V7V0/TcEEJFvxh+SQTBuLP9sMQDhGr3z+Tp3yY
            isuBZ1BTqNX+a8CFRnEN+YI43VYl3hBPBYRLwo4a2nmtFyMaOnidijxl9HDnk3LU
            aAEJAhUw5wDyNG2SKOnE3zjkknJH/1e/3k8C9iaY5gEikO9F9BTawLnzFLGdsXYg
            tIFUQDCm6Uu7jFPndP8LZXBRvSRQenKJfBJFaoJkbf2aN+1Swc3gCq4FzIIDPEJ5
            VCPeAzi78vAw
            =dP1k
            -----END PGP MESSAGE-----
          fp: 0F778AB50C03EB5A23877A080943CC1360A9D7F0
        - created_at: "2021-10-28T16:42:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5xaOfZxjCipAQ/8DkUp80kP5nqQPJaNGsWQ/DzZjNjGv1685qhb7OiB+1MO
            FY7jwaTQDPtB/TxvYkiXq1jQW/Sfg4NVvpflWqHXIK5JCZhYN8QRy7W+/ygW8w1P
            zgjBmRFdy5CA/XgpK3ivReUmY53qYyW/gwM65D6F+nXMeAL4AR7Ub8nDO7bc3uRy
            c3eEHYzi6ZSYhoQOBRM9ZNodq7bVsna77FNCLZ369qnfr2hqjybtoBQ24mLRLAnc
            XeI6YMPQEJw9FQvPH7llXgfTvE95TasbC0VGX/Bdph/gS2R88FL1ouw0RklZD+c7
            AqoGj7MV3JyTfc/+pTSEfBOwCBwuWGoAdOiyNH23TfjJ3mCdnCVrE4niJBrNhH+b
            2m2qtlPXO0HdrjeGuJUSPVJidedO5l8c/bUh0N9FokvXO7UjyYBXLncbGcYIC+pV
            gqQ8TEpy3ZaTvmCr368sR6hi9Mg4+UtZTfLvOHml6xRUk7jOh1MZCBLGUI3h8pYR
            Vkr2x1T/bi0Rj2UOuyULYmG+fT8MLtx74fvgmNDmH64qUo/vExRY06No3vI7znin
            p0FCzR7Xilq7t90bqmSsQMJ0cOO6+ufgp/6km09mOM7lPQ/ZBbxeogbhsAjtn+pU
            DvHqO7Oy+5LVmlVnTO4hV9F6bcw2SEwogWiy24EycnGUx0SiK0NcTT1/gxmQt2nU
            aAEJAhXMH1vBoig79csknPNH1KwOHQSzGsdw74A11zHYiS+C1ERYF+q7ymn8xs2A
            fNRUG722xcBUSfsiGKkXrI1evYWU7+QwQz7+FZ+1NMe//6PMgllBJf/AiAg7iE8+
            wv2G+kh16tDk
            =9Kcm
            -----END PGP MESSAGE-----
          fp: 6EC154334B8BA3FFD4E62F305112A42499373600
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
