---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.7.6
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  dependsOn:
    - name: rook-ceph
  values:
    toolbox:
      enabled: false
    monitoring:
      enabled: true
    dashboard:
      enabled: true
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        ingressClassName: "traefik"
        host:
          name: "rook.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "rook.${SECRET_DOMAIN}"
            secretName: "rook-ceph-dashboard-tls"
      storage:
        useAllNodes: true
        useAllDevices: true
        config:
          osdsPerDevice: "1"
    cephFileSystems: []
    cephObjectStores: []
